### ISSUE TITLE
Missing systray icon

### ISSUE THREAD

**Issue by loonycyborg** [flathub/io.github.mujx.Nheko#1]
Nheko's systray icon is missing for me unless I run the flatpak as "flatpak run --talk-name=org.kde.StatusNotifierWatcher io.github.mujx.Nheko". Seems some extra arg needs to be added in the manifest to make it work, cf https://github.com/flathub/org.nextcloud.Nextcloud/issues/9

**Comment by mujx** [comment]
Thanks for the report! Just pushed a [fix](https://github.com/flathub/io.github.mujx.Nheko/commit/077b7b4104f0023279081a42bc1faec60afd5af7).
